cmd_/mnt/hgfs/SI/EmbeddedStu/Linux-driver/more_module/param_2.o := arm-linux-gcc -Wp,-MD,/mnt/hgfs/SI/EmbeddedStu/Linux-driver/more_module/.param_2.o.d  -nostdinc -isystem /home/lyh/my-work/arm-sdk/opt/FriendlyARM/toolschain/4.4.3/bin/../lib/gcc/arm-none-linux-gnueabi/4.4.3/include -I/home/lyh/my-work/6818/6818GEC/kernel/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include /home/lyh/my-work/6818/6818GEC/kernel/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-s5p6818/include -Iarch/arm/plat-s5p6818/include -I/home/lyh/my-work/6818/6818GEC/kernel/arch/arm/plat-s5p6818/common -I/home/lyh/my-work/6818/6818GEC/kernel/arch/arm/plat-s5p6818/GEC6818/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -marm -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -I/home/lyh/my-work/6818/6818GEC/kernel/arch/arm/mach-s5p6818/prototype/base -I/home/lyh/my-work/6818/6818GEC/kernel/arch/arm/mach-s5p6818/prototype/module -I/home/lyh/my-work/6818/6818GEC/kernel/arch/arm/mach-s5p6818/prototype/module -D__LINUX__ -D__PRINTK__ -DNX_RELEASE -mfpu=vfp -mfloat-abi=softfp -I/home/lyh/my-work/6818/6818GEC/kernel/arch/arm/plat-s5p6818/common -I/home/lyh/my-work/6818/6818GEC/kernel/arch/arm/plat-s5p6818/GEC6818/include -Wframe-larger-than=1024 -fno-stack-protector -fomit-frame-pointer -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(param_2)"  -D"KBUILD_MODNAME=KBUILD_STR(param_drv)" -c -o /mnt/hgfs/SI/EmbeddedStu/Linux-driver/more_module/param_2.o /mnt/hgfs/SI/EmbeddedStu/Linux-driver/more_module/param_2.c

source_/mnt/hgfs/SI/EmbeddedStu/Linux-driver/more_module/param_2.o := /mnt/hgfs/SI/EmbeddedStu/Linux-driver/more_module/param_2.c

deps_/mnt/hgfs/SI/EmbeddedStu/Linux-driver/more_module/param_2.o := \

/mnt/hgfs/SI/EmbeddedStu/Linux-driver/more_module/param_2.o: $(deps_/mnt/hgfs/SI/EmbeddedStu/Linux-driver/more_module/param_2.o)

$(deps_/mnt/hgfs/SI/EmbeddedStu/Linux-driver/more_module/param_2.o):
